2014/04/13 12:38:03 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'posuser'@'localhost' (using password: YES)' in /var/www/posproject/framework/db/CDbConnection.php:381
Stack trace:
#0 /var/www/posproject/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/posproject/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/posproject/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/posproject/framework/base/CApplication.php(438): CModule->getComponent('db')
#4 /var/www/posproject/framework/db/ar/CActiveRecord.php(623): CApplication->getDb()
#5 /var/www/posproject/framework/db/ar/CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 /var/www/posproject/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/posproject/protected/models/User.php(28): CActiveRecord::model('User')
#8 /var/www/posproject/protected/components/UserIdentity.php(14): User::model()
#9 /var/www/posproject/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#10 /var/www/posproject/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#11 /var/www/posproject/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 /var/www/posproject/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#13 /var/www/posproject/framework/web/widgets/CActiveForm.php(835): CModel->validate(NULL)
#14 /var/www/posproject/protected/controllers/SiteController.php(97): CActiveForm::validate(Object(LoginForm))
#15 /var/www/posproject/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#16 /var/www/posproject/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#17 /var/www/posproject/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#18 /var/www/posproject/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#19 /var/www/posproject/framework/web/CWebApplication.php(282): CController->run('login')
#20 /var/www/posproject/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#21 /var/www/posproject/framework/base/CApplication.php(169): CWebApplication->processRequest()
#22 /var/www/posproject/index.php(13): CApplication->run()
#23 {main}
REQUEST_URI=/posproject/index.php/site/login
HTTP_REFERER=http://localhost/posproject/index.php/site/login
---
2014/04/13 12:38:03 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'posuser'@'localhost' (using password: YES)' in /var/www/posproject/framework/db/CDbConnection.php:381
Stack trace:
#0 /var/www/posproject/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/posproject/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/posproject/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/posproject/framework/base/CApplication.php(438): CModule->getComponent('db')
#4 /var/www/posproject/framework/db/ar/CActiveRecord.php(623): CApplication->getDb()
#5 /var/www/posproject/framework/db/ar/CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 /var/www/posproject/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/posproject/protected/models/User.php(28): CActiveRecord::model('User')
#8 /var/www/posproject/protected/components/UserIdentity.php(14): User::model()
#9 /var/www/posproject/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#10 /var/www/posproject/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#11 /var/www/posproject/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 /var/www/posproject/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#13 /var/www/posproject/protected/controllers/SiteController.php(106): CModel->validate()
#14 /var/www/posproject/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#15 /var/www/posproject/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#16 /var/www/posproject/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#17 /var/www/posproject/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/posproject/framework/web/CWebApplication.php(282): CController->run('login')
#19 /var/www/posproject/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#20 /var/www/posproject/framework/base/CApplication.php(169): CWebApplication->processRequest()
#21 /var/www/posproject/index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/posproject/index.php/site/login
HTTP_REFERER=http://localhost/posproject/index.php/site/login
---
2014/04/13 12:46:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'posuser'@'localhost' (using password: YES)' in /var/www/posproject/framework/db/CDbConnection.php:381
Stack trace:
#0 /var/www/posproject/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/posproject/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/posproject/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/posproject/framework/base/CApplication.php(438): CModule->getComponent('db')
#4 /var/www/posproject/framework/db/ar/CActiveRecord.php(623): CApplication->getDb()
#5 /var/www/posproject/framework/db/ar/CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 /var/www/posproject/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/posproject/protected/models/User.php(28): CActiveRecord::model('User')
#8 /var/www/posproject/protected/components/UserIdentity.php(14): User::model()
#9 /var/www/posproject/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#10 /var/www/posproject/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#11 /var/www/posproject/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 /var/www/posproject/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#13 /var/www/posproject/framework/web/widgets/CActiveForm.php(835): CModel->validate(NULL)
#14 /var/www/posproject/protected/controllers/SiteController.php(97): CActiveForm::validate(Object(LoginForm))
#15 /var/www/posproject/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#16 /var/www/posproject/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#17 /var/www/posproject/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#18 /var/www/posproject/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#19 /var/www/posproject/framework/web/CWebApplication.php(282): CController->run('login')
#20 /var/www/posproject/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#21 /var/www/posproject/framework/base/CApplication.php(169): CWebApplication->processRequest()
#22 /var/www/posproject/index.php(13): CApplication->run()
#23 {main}
REQUEST_URI=/posproject/index.php/site/login
HTTP_REFERER=http://localhost/posproject/index.php/site/login
---
2014/04/13 12:46:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'posuser'@'localhost' (using password: YES)' in /var/www/posproject/framework/db/CDbConnection.php:381
Stack trace:
#0 /var/www/posproject/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/posproject/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/posproject/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/posproject/framework/base/CApplication.php(438): CModule->getComponent('db')
#4 /var/www/posproject/framework/db/ar/CActiveRecord.php(623): CApplication->getDb()
#5 /var/www/posproject/framework/db/ar/CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 /var/www/posproject/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/posproject/protected/models/User.php(28): CActiveRecord::model('User')
#8 /var/www/posproject/protected/components/UserIdentity.php(14): User::model()
#9 /var/www/posproject/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#10 /var/www/posproject/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#11 /var/www/posproject/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 /var/www/posproject/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#13 /var/www/posproject/framework/web/widgets/CActiveForm.php(835): CModel->validate(NULL)
#14 /var/www/posproject/protected/controllers/SiteController.php(97): CActiveForm::validate(Object(LoginForm))
#15 /var/www/posproject/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#16 /var/www/posproject/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#17 /var/www/posproject/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#18 /var/www/posproject/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#19 /var/www/posproject/framework/web/CWebApplication.php(282): CController->run('login')
#20 /var/www/posproject/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#21 /var/www/posproject/framework/base/CApplication.php(169): CWebApplication->processRequest()
#22 /var/www/posproject/index.php(13): CApplication->run()
#23 {main}
REQUEST_URI=/posproject/index.php/site/login
HTTP_REFERER=http://localhost/posproject/index.php/site/login
---
2014/04/13 12:46:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'posuser'@'localhost' (using password: YES)' in /var/www/posproject/framework/db/CDbConnection.php:381
Stack trace:
#0 /var/www/posproject/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/posproject/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/posproject/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/posproject/framework/base/CApplication.php(438): CModule->getComponent('db')
#4 /var/www/posproject/framework/db/ar/CActiveRecord.php(623): CApplication->getDb()
#5 /var/www/posproject/framework/db/ar/CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 /var/www/posproject/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/posproject/protected/models/User.php(28): CActiveRecord::model('User')
#8 /var/www/posproject/protected/components/UserIdentity.php(14): User::model()
#9 /var/www/posproject/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#10 /var/www/posproject/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#11 /var/www/posproject/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 /var/www/posproject/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#13 /var/www/posproject/protected/controllers/SiteController.php(106): CModel->validate()
#14 /var/www/posproject/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#15 /var/www/posproject/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#16 /var/www/posproject/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#17 /var/www/posproject/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/posproject/framework/web/CWebApplication.php(282): CController->run('login')
#19 /var/www/posproject/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#20 /var/www/posproject/framework/base/CApplication.php(169): CWebApplication->processRequest()
#21 /var/www/posproject/index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/posproject/index.php/site/login
HTTP_REFERER=http://localhost/posproject/index.php/site/login
---
2014/04/13 12:47:04 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'posuser'@'localhost' (using password: YES)' in /var/www/posproject/framework/db/CDbConnection.php:381
Stack trace:
#0 /var/www/posproject/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/posproject/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/posproject/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/posproject/framework/base/CApplication.php(438): CModule->getComponent('db')
#4 /var/www/posproject/framework/db/ar/CActiveRecord.php(623): CApplication->getDb()
#5 /var/www/posproject/framework/db/ar/CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 /var/www/posproject/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/posproject/protected/models/User.php(28): CActiveRecord::model('User')
#8 /var/www/posproject/protected/components/UserIdentity.php(14): User::model()
#9 /var/www/posproject/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#10 /var/www/posproject/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#11 /var/www/posproject/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 /var/www/posproject/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#13 /var/www/posproject/protected/controllers/SiteController.php(106): CModel->validate()
#14 /var/www/posproject/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#15 /var/www/posproject/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#16 /var/www/posproject/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#17 /var/www/posproject/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/posproject/framework/web/CWebApplication.php(282): CController->run('login')
#19 /var/www/posproject/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#20 /var/www/posproject/framework/base/CApplication.php(169): CWebApplication->processRequest()
#21 /var/www/posproject/index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/posproject/index.php/site/login
HTTP_REFERER=http://localhost/posproject/index.php/site/login
---
2014/04/13 12:54:09 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'posuser'@'localhost' (using password: YES)' in /var/www/posproject/framework/db/CDbConnection.php:381
Stack trace:
#0 /var/www/posproject/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/posproject/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/posproject/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/posproject/framework/base/CApplication.php(438): CModule->getComponent('db')
#4 /var/www/posproject/framework/db/ar/CActiveRecord.php(623): CApplication->getDb()
#5 /var/www/posproject/framework/db/ar/CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 /var/www/posproject/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/posproject/protected/models/User.php(28): CActiveRecord::model('User')
#8 /var/www/posproject/protected/components/UserIdentity.php(14): User::model()
#9 /var/www/posproject/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#10 /var/www/posproject/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#11 /var/www/posproject/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 /var/www/posproject/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#13 /var/www/posproject/protected/controllers/SiteController.php(106): CModel->validate()
#14 /var/www/posproject/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#15 /var/www/posproject/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#16 /var/www/posproject/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#17 /var/www/posproject/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/posproject/framework/web/CWebApplication.php(282): CController->run('login')
#19 /var/www/posproject/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#20 /var/www/posproject/framework/base/CApplication.php(169): CWebApplication->processRequest()
#21 /var/www/posproject/index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/posproject/index.php/site/login
HTTP_REFERER=http://localhost/posproject/index.php/site/login
---
2014/04/13 12:54:12 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'posuser'@'localhost' (using password: YES)' in /var/www/posproject/framework/db/CDbConnection.php:381
Stack trace:
#0 /var/www/posproject/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/posproject/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/posproject/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/posproject/framework/base/CApplication.php(438): CModule->getComponent('db')
#4 /var/www/posproject/framework/db/ar/CActiveRecord.php(623): CApplication->getDb()
#5 /var/www/posproject/framework/db/ar/CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 /var/www/posproject/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/posproject/protected/models/User.php(28): CActiveRecord::model('User')
#8 /var/www/posproject/protected/components/UserIdentity.php(14): User::model()
#9 /var/www/posproject/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#10 /var/www/posproject/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#11 /var/www/posproject/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 /var/www/posproject/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#13 /var/www/posproject/protected/controllers/SiteController.php(106): CModel->validate()
#14 /var/www/posproject/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#15 /var/www/posproject/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#16 /var/www/posproject/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#17 /var/www/posproject/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/posproject/framework/web/CWebApplication.php(282): CController->run('login')
#19 /var/www/posproject/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#20 /var/www/posproject/framework/base/CApplication.php(169): CWebApplication->processRequest()
#21 /var/www/posproject/index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/posproject/index.php/site/login
HTTP_REFERER=http://localhost/posproject/index.php/site/login
---
2014/04/13 12:54:23 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'posuser'@'localhost' (using password: YES)' in /var/www/posproject/framework/db/CDbConnection.php:381
Stack trace:
#0 /var/www/posproject/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/posproject/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/posproject/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/posproject/framework/base/CApplication.php(438): CModule->getComponent('db')
#4 /var/www/posproject/framework/db/ar/CActiveRecord.php(623): CApplication->getDb()
#5 /var/www/posproject/framework/db/ar/CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 /var/www/posproject/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/posproject/protected/models/User.php(28): CActiveRecord::model('User')
#8 /var/www/posproject/protected/components/UserIdentity.php(14): User::model()
#9 /var/www/posproject/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#10 /var/www/posproject/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#11 /var/www/posproject/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 /var/www/posproject/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#13 /var/www/posproject/protected/controllers/SiteController.php(106): CModel->validate()
#14 /var/www/posproject/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#15 /var/www/posproject/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#16 /var/www/posproject/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#17 /var/www/posproject/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/posproject/framework/web/CWebApplication.php(282): CController->run('login')
#19 /var/www/posproject/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#20 /var/www/posproject/framework/base/CApplication.php(169): CWebApplication->processRequest()
#21 /var/www/posproject/index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/posproject/index.php/site/login
HTTP_REFERER=http://localhost/posproject/index.php/site/login
---
2014/04/13 12:56:13 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2005] Unknown MySQL server host '127.0.0.1:3306' (2)' in /var/www/posproject/framework/db/CDbConnection.php:381
Stack trace:
#0 /var/www/posproject/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/posproject/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/posproject/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/posproject/framework/base/CApplication.php(438): CModule->getComponent('db')
#4 /var/www/posproject/framework/db/ar/CActiveRecord.php(623): CApplication->getDb()
#5 /var/www/posproject/framework/db/ar/CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 /var/www/posproject/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/posproject/protected/models/User.php(28): CActiveRecord::model('User')
#8 /var/www/posproject/protected/components/UserIdentity.php(14): User::model()
#9 /var/www/posproject/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#10 /var/www/posproject/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#11 /var/www/posproject/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 /var/www/posproject/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#13 /var/www/posproject/protected/controllers/SiteController.php(106): CModel->validate()
#14 /var/www/posproject/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#15 /var/www/posproject/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#16 /var/www/posproject/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#17 /var/www/posproject/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/posproject/framework/web/CWebApplication.php(282): CController->run('login')
#19 /var/www/posproject/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#20 /var/www/posproject/framework/base/CApplication.php(169): CWebApplication->processRequest()
#21 /var/www/posproject/index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/posproject/index.php/site/login
HTTP_REFERER=http://localhost/posproject/index.php/site/login
---
2014/04/13 12:56:29 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2005] Unknown MySQL server host '127.0.0.1:3306' (2)' in /var/www/posproject/framework/db/CDbConnection.php:381
Stack trace:
#0 /var/www/posproject/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/posproject/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/posproject/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/posproject/framework/base/CApplication.php(438): CModule->getComponent('db')
#4 /var/www/posproject/framework/db/ar/CActiveRecord.php(623): CApplication->getDb()
#5 /var/www/posproject/framework/db/ar/CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 /var/www/posproject/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/posproject/protected/models/User.php(28): CActiveRecord::model('User')
#8 /var/www/posproject/protected/components/UserIdentity.php(14): User::model()
#9 /var/www/posproject/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#10 /var/www/posproject/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#11 /var/www/posproject/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 /var/www/posproject/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#13 /var/www/posproject/protected/controllers/SiteController.php(106): CModel->validate()
#14 /var/www/posproject/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#15 /var/www/posproject/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#16 /var/www/posproject/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#17 /var/www/posproject/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/posproject/framework/web/CWebApplication.php(282): CController->run('login')
#19 /var/www/posproject/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#20 /var/www/posproject/framework/base/CApplication.php(169): CWebApplication->processRequest()
#21 /var/www/posproject/index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/posproject/index.php/site/login
HTTP_REFERER=http://localhost/posproject/index.php/site/login
---
2014/04/13 12:56:29 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2005] Unknown MySQL server host '127.0.0.1:3306' (2)' in /var/www/posproject/framework/db/CDbConnection.php:381
Stack trace:
#0 /var/www/posproject/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/posproject/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/posproject/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/posproject/framework/base/CApplication.php(438): CModule->getComponent('db')
#4 /var/www/posproject/framework/db/ar/CActiveRecord.php(623): CApplication->getDb()
#5 /var/www/posproject/framework/db/ar/CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 /var/www/posproject/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/posproject/protected/models/User.php(28): CActiveRecord::model('User')
#8 /var/www/posproject/protected/components/UserIdentity.php(14): User::model()
#9 /var/www/posproject/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#10 /var/www/posproject/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#11 /var/www/posproject/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#12 /var/www/posproject/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#13 /var/www/posproject/framework/web/widgets/CActiveForm.php(835): CModel->validate(NULL)
#14 /var/www/posproject/protected/controllers/SiteController.php(97): CActiveForm::validate(Object(LoginForm))
#15 /var/www/posproject/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#16 /var/www/posproject/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#17 /var/www/posproject/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#18 /var/www/posproject/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#19 /var/www/posproject/framework/web/CWebApplication.php(282): CController->run('login')
#20 /var/www/posproject/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#21 /var/www/posproject/framework/base/CApplication.php(169): CWebApplication->processRequest()
#22 /var/www/posproject/index.php(13): CApplication->run()
#23 {main}
REQUEST_URI=/posproject/index.php/site/login
HTTP_REFERER=http://localhost/posproject/index.php/site/login
---
